version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: flaskmysql           
      MYSQL_USER: myuser                   
      MYSQL_PASSWORD: mypassword           
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:

